<?xml version="1.0"?>
<robot>
	<include filename="$(find cob_calibration_data)/raw3-1/calibration/calibration_default.urdf.xacro" />
	<include filename="$(find cob_calibration_data)/raw3-1/calibration/calibration_offset.urdf.xacro" />>

	<!-- *********************** -->
	<!-- upper robot calibration -->
	<!-- *********************** -->
	<!-- torso mount positions | relative to base_link -->
	<property name="torso_x" value="${def_torso_x+offset_torso_x}"/>
	<property name="torso_y" value="${def_torso_y+offset_torso_y}"/>
	<property name="torso_z" value="${def_torso_z+offset_torso_z}"/>
	<property name="torso_roll" value="${def_torso_roll+offset_torso_roll}"/>
	<property name="torso_pitch" value="${def_torso_pitch+offset_torso_pitch}"/>
	<property name="torso_yaw" value="${def_torso_yaw+offset_torso_yaw}"/>

	<!-- arm mount positions | relative to base_link -->
	<property name="arm_x" value="${def_arm_x+offset_arm_x}"/>
	<property name="arm_y" value="${def_arm_y+offset_arm_y}"/>
	<property name="arm_z" value="${def_arm_z+offset_arm_z}"/>
	<property name="arm_roll" value="${def_arm_roll+offset_arm_roll}"/>
	<property name="arm_pitch" value="${def_arm_pitch+offset_arm_pitch}"/>
	<property name="arm_yaw" value="${def_arm_yaw+offset_arm_yaw}"/>


	<!-- ***************************** -->
	<!-- camera calibration properties -->
	<!-- ***************************** -->
	<!-- left | handeye calibration | relative to head_axis_link -->
	<property name="cam_ref_x" value="${def_cam_ref_x+offset_cam_ref_x}"/>
	<property name="cam_ref_y" value="${def_cam_ref_y+offset_cam_ref_y}"/>
	<property name="cam_ref_z" value="${def_cam_ref_z+offset_cam_ref_z}"/>
	<property name="cam_ref_roll" value="${def_cam_ref_roll+offset_cam_ref_roll}"/>
	<property name="cam_ref_pitch" value="${def_cam_ref_pitch+offset_cam_ref_pitch}"/>
	<property name="cam_ref_yaw" value="${def_cam_ref_yaw+offset_cam_ref_yaw}"/>

	<!-- right | stereo baseline calibration | relative to left camera -->
	<property name="cam_r_x" value="${def_cam_r_x+offset_cam_r_x}"/>
	<property name="cam_r_y" value="${def_cam_r_y+offset_cam_r_y}"/>
	<property name="cam_r_z" value="${def_cam_r_z+offset_cam_r_z}"/>
	<property name="cam_r_roll" value="${def_cam_r_roll+offset_cam_r_roll}"/>
	<property name="cam_r_pitch" value="${def_cam_r_pitch+offset_cam_r_pitch}"/>
	<property name="cam_r_yaw" value="${def_cam_r_yaw+offset_cam_r_yaw}"/>

	<!-- cam3d | handeye calibration | relative to head_axis_link -->
	<property name="cam3d_x" value="${def_cam3d_x+offset_cam3d_x}"/>
	<property name="cam3d_y" value="${def_cam3d_y+offset_cam3d_y}"/>
	<property name="cam3d_z" value="${def_cam3d_z+offset_cam3d_z}"/>
	<property name="cam3d_roll" value="${def_cam3d_roll+offset_cam3d_roll}"/>
	<property name="cam3d_pitch" value="${def_cam3d_pitch+offset_cam3d_pitch}"/>
	<property name="cam3d_yaw" value="${def_cam3d_yaw+offset_cam3d_yaw}"/>
</robot>
